const db = require("../models");
const { sendMail } = require("../middleware/mailer");
const ContactInfo = db.ContactInfo;

/**
 * 🔹 Professional Email Wrapper
 * Designed for maximum compatibility with Gmail, Outlook, and Apple Mail.
 */
const emailTemplate = (content, title) => `
  <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #334155; max-width: 600px; margin: 20px auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
    <div style="background: #1e293b; padding: 30px 20px; text-align: center;">
      <h1 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1.5px; text-transform: uppercase; font-weight: 800;">Aswath Hollow Bricks</h1>
      <p style="color: #94a3b8; margin: 5px 0 0 0; font-size: 13px; font-weight: 500;">Premium Construction & Lorry Services</p>
    </div>
    
    <div style="padding: 40px 30px; background: #ffffff;">
      <h2 style="color: #0f172a; margin-top: 0; font-size: 18px; border-left: 4px solid #10b981; padding-left: 15px;">${title}</h2>
      <div style="margin-top: 20px;">
        ${content}
      </div>
    </div>
    
    <div style="background: #f8fafc; padding: 25px; text-align: center; border-top: 1px solid #e2e8f0;">
      <p style="margin: 0; font-size: 13px; color: #64748b; font-weight: 600;">Tiruppur, Tamil Nadu</p>
      <p style="margin: 5px 0 0 0; font-size: 11px; color: #94a3b8;">&copy; 2026 Aswath Hollow Bricks. This is an automated system notification.</p>
    </div>
  </div>
`;

// CREATE CONTACT
exports.createContact = async (req, res) => {
  try {
    const { name, phone, email } = req.body;
    
    // Save to Database
    const data = await ContactInfo.create({
      name,
      phone,
      email,
      isviewed: false,
    });

    // 1️⃣ USER CONFIRMATION EMAIL
    const userContent = `
      <p style="font-size: 16px;">Hello <strong>${name}</strong>,</p>
      <p>Thank you for choosing <strong>Aswath Hollow Bricks</strong>. We've received your request and our team is already reviewing it.</p>
      
      <div style="background: #f0fdf4; border: 1px solid #bbf7d0; padding: 20px; border-radius: 12px; margin: 25px 0;">
        <p style="margin: 0; font-weight: bold; color: #166534; font-size: 14px;">What Happens Next?</p>
        <p style="margin: 5px 0 0 0; color: #15803d; font-size: 14px;">One of our representatives will contact you at <strong>${phone}</strong> within 24 hours to discuss your requirements.</p>
      </div>
      
      <p style="font-size: 14px; color: #64748b;">If you need immediate assistance, simply reply to this email.</p>
      <br/>
      <p style="margin: 0; font-weight: bold; color: #1e293b;">Best Regards,</p>
      <p style="margin: 0; color: #64748b;">Aswath Team</p>
    `;

    // Important: passing the HTML generated by the template
    await sendMail(
      email,
      "We've received your inquiry - Aswath Hollow Bricks",
      emailTemplate(userContent, "Request Received")
    );

    // 2️⃣ ADMIN ALERT EMAIL
    const adminContent = `
      <p style="font-size: 15px; color: #334155;">You have a new lead from the website contact form:</p>
      
      <div style="border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; margin: 20px 0;">
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <tr style="background: #f8fafc;">
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #64748b; width: 35%;">Customer</td>
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; color: #1e293b; font-weight: 600;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #64748b;">Phone</td>
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0;">
              <a href="tel:${phone}" style="color: #2563eb; text-decoration: none; font-weight: bold;">${phone}</a>
            </td>
          </tr>
          <tr style="background: #f8fafc;">
            <td style="padding: 12px 15px; font-weight: bold; color: #64748b;">Email</td>
            <td style="padding: 12px 15px; color: #1e293b;">${email}</td>
          </tr>
        </table>
      </div>
      
      <div style="margin-top: 30px; text-align: center;">
        <a href="tel:${phone}" style="background: #10b981; color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 10px; font-weight: bold; font-size: 14px; display: inline-block;">CALL CUSTOMER NOW</a>
      </div>
    `;

    await sendMail(
      "bricksync001@gmail.com",
      "🚨 New Lead: " + name,
      emailTemplate(adminContent, "New Callback Request")
    );

    res.json({ success: true, data });
  } catch (err) {
    console.error("Mail Error:", err);
    res.status(500).json({ error: err.message });
  }
};

// GET ALL CONTACTS
exports.getContacts = async (req, res) => {
  try {
    const contacts = await ContactInfo.findAll({
      order: [["createdAt", "DESC"]],
    });
    res.json(contacts);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// MARK AS VIEWED
exports.markViewed = async (req, res) => {
  try {
    const { id } = req.params;
    await ContactInfo.update(
      { isviewed: true },
      { where: { id } }
    );
    res.json({ message: "Marked as viewed" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};